fastlane_version "2.28.3"

default_platform :ios

skip_docs

platform :ios do
	before_all do

	end

	desc "Code signing sync"
	lane :certificates do |params|
		type = params[:type] || 'development'
		match(type: type)
	end

	after_all do |lane|
		clean_build_artifacts
	end

	error do |lane, exception|

	end
end
